version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor: 
      name: win/default
    steps:
      - checkout
      - run:
          name: "build verification"
          command: dotnet build
  test:
    executor: 
      name: win/default
    steps:
      - checkout
      - run: 
          name: "unit tests"
          command: |
            dotnet test 
  publish:
    executor: 
      name: win/default
    steps:
      - checkout
      - run:
          name: "publish and create artifact"
          command: |
            dotnet publish -c Release -r win10-x64
            Compress-Archive C:\Users\circleci\project\User_interface\bin\Release\netcoreapp3.0\win10-x64\publish Uceni_Jazyku.zip
      - store_artifacts:
          path: Uceni_Jazyku.zip

workflows:
  version: 2
  build-test-publish:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              ignore:
                - publish
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - publish
