version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor: 
      name: win/vs2019
    steps:
      - checkout
      - run: dotnet build
      - run: dotnet test --filter ClassName=UnitTests.CycleServiceTests
      - run: dotnet test --filter ClassName=UnitTests.CycleFactoryTests
      - run: dotnet test --filter ClassName=UnitTests.CycleDatabaseTests