//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uceni_jazyku.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uceni_jazyku.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;language&gt;
        ///  &lt;iso_code&gt;cs_CZ&lt;/iso_code&gt;
        ///  &lt;language_name&gt;
        ///    &lt;name&gt;Čeština&lt;/name&gt;
        ///  &lt;/language_name&gt;
        ///  &lt;words&gt;
        ///    &lt;word&gt;
        ///      &lt;value&gt;a&lt;/value&gt;
        ///      &lt;categories&gt;
        ///        &lt;category id=&quot;lecture&quot;&gt;1A&lt;/category&gt;
        ///      &lt;/categories&gt;
        ///      &lt;translation&gt;
        ///        &lt;target_language name=&quot;Němčina&quot;&gt;und&lt;/target_language&gt;
        ///      &lt;/translation&gt;
        ///    &lt;/word&gt;
        ///    &lt;word&gt;
        ///      &lt;value&gt;Ahoj!&lt;/value&gt;
        ///      &lt;categories&gt;
        ///        &lt;category id=&quot;lecture&quot;&gt;1A&lt;/category&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Čeština {
            get {
                return ResourceManager.GetString("Čeština", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I [swim] across a river.
        ///He [runs] very quickly.
        ///We [learn] on Monday exam.
        ///.
        /// </summary>
        internal static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Data&gt;
        ///  &lt;Priklad&gt;
        ///    &lt;Veta&gt;I _______ across a river.&lt;/Veta&gt;
        ///    &lt;Slovo&gt;swim&lt;/Slovo&gt;
        ///  &lt;/Priklad&gt;
        ///  &lt;Priklad&gt;
        ///    &lt;Veta&gt;He _______ very quickly.&lt;/Veta&gt;
        ///    &lt;Slovo&gt;runs&lt;/Slovo&gt;
        ///  &lt;/Priklad&gt;
        ///  &lt;Priklad&gt;
        ///    &lt;Veta&gt;We _______ on Monday exam.&lt;/Veta&gt;
        ///    &lt;Slovo&gt;learn&lt;/Slovo&gt;
        ///  &lt;/Priklad&gt;
        ///&lt;/Data&gt;
        ///.
        /// </summary>
        internal static string data1 {
            get {
                return ResourceManager.GetString("data1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello-Ahoj
        ///number-číslo.
        /// </summary>
        internal static string dataWords {
            get {
                return ResourceManager.GetString("dataWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Data&gt;
        ///  &lt;Priklad&gt;
        ///    &lt;Zdrojovy_jazyk&gt;Ahoj&lt;/Zdrojovy_jazyk&gt;
        ///    &lt;Cilovy_jazyk&gt;Hello&lt;/Cilovy_jazyk&gt;
        ///  &lt;/Priklad&gt;
        ///  &lt;Priklad&gt;
        ///    &lt;Zdrojovy_jazyk&gt;číslo&lt;/Zdrojovy_jazyk&gt;
        ///    &lt;Cilovy_jazyk&gt;number&lt;/Cilovy_jazyk&gt;
        ///  &lt;/Priklad&gt;
        ///&lt;/Data&gt;
        ///.
        /// </summary>
        internal static string dataWords1 {
            get {
                return ResourceManager.GetString("dataWords1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;eval&gt;
        ///  &lt;Testovy_priklad&gt;
        ///    &lt;vysledek&gt;Spravne&lt;/vysledek&gt;
        ///    &lt;Zadani&gt;Ahoj&lt;/Zadani&gt;
        ///    &lt;Ocekavana_odpoved&gt;Hello&lt;/Ocekavana_odpoved&gt;
        ///    &lt;Odpoved&gt;Hello&lt;/Odpoved&gt;
        ///  &lt;/Testovy_priklad&gt;
        ///  &lt;Testovy_priklad&gt;
        ///    &lt;vysledek&gt;Spravne&lt;/vysledek&gt;
        ///    &lt;Zadani&gt;číslo&lt;/Zadani&gt;
        ///    &lt;Ocekavana_odpoved&gt;number&lt;/Ocekavana_odpoved&gt;
        ///    &lt;Odpoved&gt;number&lt;/Odpoved&gt;
        ///  &lt;/Testovy_priklad&gt;
        ///&lt;/eval&gt;
        ///.
        /// </summary>
        internal static string evaluation {
            get {
                return ResourceManager.GetString("evaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;language&gt;
        ///  &lt;iso_code&gt;de-DE&lt;/iso_code&gt;
        ///  &lt;language_name&gt;
        ///    &lt;name&gt;Němčina&lt;/name&gt;
        ///    &lt;name&gt;Germany&lt;/name&gt;
        ///    &lt;name&gt;Deutsch&lt;/name&gt;
        ///  &lt;/language_name&gt;
        ///  &lt;words&gt;
        ///    &lt;word&gt;
        ///      &lt;value&gt;arbeiten&lt;/value&gt;
        ///      &lt;categories&gt;
        ///        &lt;category id=&quot;lecture&quot;&gt;1A&lt;/category&gt;
        ///      &lt;/categories&gt;
        ///      &lt;translation&gt;
        ///        &lt;target_language name=&quot;Čeština&quot;&gt;pracovat&lt;/target_language&gt;
        ///      &lt;/translation&gt;
        ///    &lt;/word&gt;
        ///    &lt;word&gt;
        ///      &lt;value&gt;Danke.&lt;/value&gt;
        ///      &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Germany {
            get {
                return ResourceManager.GetString("Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;language&gt;
        ///  &lt;language_name&gt;
        ///    &lt;name&gt;Němčina&lt;/name&gt;
        ///    &lt;name&gt;Germany&lt;/name&gt;
        ///    &lt;name&gt;Deutsch&lt;/name&gt;
        ///  &lt;/language_name&gt;
        ///  &lt;words&gt;
        ///    &lt;word&gt;
        ///      &lt;value&gt;arbeiten&lt;/value&gt;
        ///      &lt;categories&gt;
        ///        &lt;category id=&quot;lecture&quot;&gt;1A&lt;/category&gt;
        ///      &lt;/categories&gt;
        ///      &lt;translation&gt;
        ///        &lt;target_language name=&quot;Čeština&quot;&gt;pracovat&lt;/target_language&gt;
        ///      &lt;/translation&gt;
        ///    &lt;/word&gt;
        ///  &lt;/words&gt;
        ///&lt;/language&gt;
        ///.
        /// </summary>
        internal static string Germany___kopie {
            get {
                return ResourceManager.GetString("Germany___kopie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [language=Němčina|Čeština]
        ///[category=lecture(1A)]
        ///arbeiten-pracovat
        ///ich arbeite-pracuji
        ///der-ten
        ///die-ta
        ///das-to
        ///dir-tobě
        ///dir-ti
        ///du-ty
        ///fertig-hotový
        ///Freund-přítel
        ///Freundin-přítelkyně
        ///gut-dobrý
        ///gut-dobře
        ///ich-já
        ///ich bin-jsem
        ///mein-můj
        ///meine-moje
        ///mir-mně
        ///noch-ještě
        ///schon-už
        ///schon-již
        ///studieren-studovat
        ///ich studiere-studuji
        ///du studierst-studuješ
        ///und-a
        ///wer-kdo
        ///wir-my
        ///wir sind-jsme
        ///Hallo!-Ahoj!
        ///Wie geht&apos;s?-Jak se daří?
        ///Es geht.-Ujde to.
        ///seit langem-odedávna
        ///wir sind befreundet-přátel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lekce1_němčina {
            get {
                return ResourceManager.GetString("lekce1_němčina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Test_Odpovedi {
            get {
                return ResourceManager.GetString("Test_Odpovedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;user&gt;
        ///  &lt;name&gt;Tester&lt;/name&gt;
        ///  &lt;good_answers&gt;7&lt;/good_answers&gt;
        ///  &lt;bad_answers&gt;3&lt;/bad_answers&gt;
        ///&lt;/user&gt;
        ///.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
    }
}
